### ISSUE TITLE
Starting HTML

### ISSUE THREAD

**Issue by FraMarcuccio** [FraMarcuccio/EnergyHeaven#1]
Base html code to test the contract

**Comment by FraMarcuccio** [comment]
Created html base

**Comment by byungster** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Hamdyx, @gwho, @al3mart, @honeykjoule, @A-qiu161203, @enricomarchesin, @Maharshi-Pandya, @Ivkaa, @bbrietzke, @AddressXception, @jason-klein, @OliveIT, @pgrzesik, @ghislain5, @cernak, @Ssunnyy, @dilsayar, @kevinhu, @Rcperez, @ronnathaniel, @rish, @everytimeeverythingLamBa, @scalalang2, @sndnsos, @HR, @kaichen, @pjserol, @cuamckuu, @swak, @truyayong, @joffreyred, @maaznizam290, @geekchu, @jasonwbarnett, @k-maris-dew, @ctsrc, @transient-jonas, @munkacsimark, @huangzhhui, @ziljah, @Cuzo, @phantomk, @1stdevfriend, @CharesFang, @maximstanciu, @dadaphl, @leohxj, @ASchmidt1024, @spdd, @jbueza
